services:
  db-server:
    image: mysql:latest
    container_name: db-server
    restart: always
    ports:
      - "3306:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: admin         
      MYSQL_DATABASE: bankhai            
      MYSQL_USER: admin                  
      MYSQL_PASSWORD: admin               
    volumes:
      - mysql_data:/var/lib/mysql        

  phpmyadmin:
    image: phpmyadmin/phpmyadmin       
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"                        
    environment:
      PMA_HOST: db-server                
      PMA_USER: admin                    
      PMA_PASSWORD: admin                
    depends_on:
      - db-server                         

volumes:
  mysql_data:
    driver: local
